name: omifit
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  animated_snack_bar: ^0.4.0
  animations: null
  appflowy_board: null
  auto_size_text: ^3.0.0
  avatar_glow: ^3.0.1
  avatar_stack: ^1.2.0
  bouncing_widget: ^2.0.0
  cached_network_image: ^3.3.1
  change_app_package_name: ^1.1.0
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  custom_sliding_segmented_control: ^1.8.3
  dartz: ^0.10.1
  device_info_plus: ^10.1.0
  dio: ^5.3.0
  dotted_line: ^3.2.2
  dropdown_plus_plus: ^0.1.1+1
  dropdown_search: ^5.0.6
  fl_chart: ^0.68.0
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.5.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_typeahead: ^5.2.0
  fluttertoast: ^8.2.5
  freezed_annotation: ^2.4.3
  get: ^4.6.6
  get_it: ^7.2.0
  go_router: ^10.0.0
  google_fonts: ^6.2.0
  hovering: ^1.0.4
  iconly: ^1.0.1
  image_picker: ^1.0.1
  injectable: null
  intl: ^0.19.0
  logger: ^2.2.0
  lottie: ^2.7.0
  modal_bottom_sheet: ^3.0.0
  paged_datatable: ^2.1.0
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^10.2.0
  pin_code_fields: ^8.0.1
  pinput: ^3.0.1
  popover: ^0.2.8+2
  primer_progress_bar: ^0.4.2
  progress_stepper: ^1.0.0
  pull_down_button: ^0.9.4
  responsive_builder: ^0.7.0
  responsive_framework: ^1.4.0
  rive: ^0.13.4
  scrollable_table_view: ^2.0.3
  share_plus: ^7.2.2
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  simple_progress_indicators: ^0.2.0
  url_launcher: ^6.1.9
  url_strategy: ^0.2.0
  webview_flutter: ^4.0.2
  wolt_modal_sheet: ^0.5.0

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
          weight: 200
