name: omifit
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  animations: null
  appflowy_board: null
  auto_size_text: ^3.0.0
  avatar_glow: ^3.0.1
  bouncing_widget: ^2.0.0
  cached_network_image: ^3.3.1
  change_app_package_name: ^1.1.0
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  custom_sliding_segmented_control: ^1.8.1
  dartz: ^0.10.1
  dio: ^5.3.0
  fl_chart: ^0.36.0
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.5.4
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.5
  get: ^4.6.6
  get_it: ^7.2.0
  go_router: ^10.0.0
  google_fonts: ^6.2.0
  iconly: ^1.0.1
  image_picker: ^1.0.1
  injectable: null
  intl: ^0.18.0
  logger: ^2.2.0
  lottie: ^2.7.0
  permission_handler: ^10.2.0
  pin_code_fields: ^8.0.1
  pinput: ^3.0.1
  popover: ^0.2.8+2
  progress_stepper: ^1.0.0
  pull_down_button: ^0.9.4
  responsive_builder: ^0.7.0
  responsive_framework: ^1.4.0
  rive: ^0.13.4
  share_plus: ^7.2.2
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  simple_progress_indicators: ^0.2.0
  url_launcher: ^6.1.9
  url_strategy: ^0.2.0
  webview_flutter: ^4.0.2
  wolt_modal_sheet: ^0.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
          weight: 200
